---

- name: Ensure the vars are defined.
  assert: 
    that:  "{{ item }} is defined" 
  with_items:
      - postgresql_version

- name: Stop the cluster.
  become: True
  become_user: root
  service: 
    name: "postgresql-{{postgresql_version}}.service"
    state: stopped
