---

- name: Create User, Group and ssh_keys
  include: create_postgres_user.yml
  when: state in ["postgresql_create_user"]

- name: Install Postgresql instances
  include: create_postgresql.yml
  when: state in ["postgresql_create_instances"]

- name: Install Repmgr
  include: create_repmgr.yml
  when: state in ["postgresql_create_repmgr"]

- name: Configure Postgresql instances
  include: configure_postgresql.yml
  when: state in ["postgresql_configure"]

- name: Configure Repmgr Master
  include: configure_repmgr_master.yml
  when: state in ["postgresql_configure_repmgr_master"]

- name: Configure Repmgr Slaves
  include: configure_repmgr_slaves.yml
  when: state in ["postgresql_configure_repmgr_slaves"]

- name: Switchover to a standby node
  include: switchover_to_standby_node.yml
  when: state in ["postgresql_switchover_to_standby_node"]

- name: Status of the cluster
  include: cluster_status.yml
  when: state in ["postgresql_cluster_status"]

- name: Start of the cluster
  include: cluster_start.yml
  when: state in ["postgresql_cluster_start"]

- name: Stop of the cluster
  include: cluster_stop.yml
  when: state in ["postgresql_cluster_stop"]

- name: Status Repmgrd
  include: cluster_repmgrd_status.yml
  when: state in ["postgresql_cluster_repmgrd_status"]

- name: Start Repmgrd
  include: cluster_repmgrd_start.yml
  when: state in ["postgresql_cluster_repmgrd_start"]

- name: Stop Repmgrd
  include: cluster_repmgrd_stop.yml
  when: state in ["postgresql_cluster_repmgrd_stop"]

- name: Status of the cluster replication
  include: cluster_replication_status.yml
  when: state in ["postgresql_cluster_replication_status"]


# Todo:
# failover
# ip virtuelle

